Add support for UTC timestamp. Closes #103
hashicorp/go-hclog pull request #104
Opened 2021-12-15 16:48 UTC by binaek

2021-12-15 16:48 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/go-hclog?pullRequest=104)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/go-hclog?pullRequest=104)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/go-hclog?pullRequest=104).</sub>

2021-12-15 16:56 UTC, evanphx commented
Is there a reason you'd want the logs in a different timezone than the system itself? That's the reason we don't do this currently, we want the logs to always reflect the time of the system.

2021-12-15 17:24 UTC, binaek commented
@evanphx  I put in the `UTC` behind a flag for precisely the reason you mentioned. Most logs need to reflect the time of the system where it's logged from.

Having said that, `UTC` as a time zone removes a lot of ambiguities associated with local time zones and timestamps (not even bringing DST into the picture)

However, the motivation behind this PR is that we use `hclog` inside a library - which runs in an application which has its own logging and can be setup to log in UTC. The logs from our library interleave with the application's log and appear in the same log destination.

2021-12-17 22:16 UTC, evanphx commented
@binaek Gotcha, that makes sense. I'm wondering if rather than just a flag to set UTC, we should allow for someone to pass in a function that returns the current time. That would allow them maximum flexibility to calculate the current time in whatever form they want.

2021-12-17 22:27 UTC, binaek commented
@evanphx That sounds like a good approach. Let me have a dig and update the PR.

2021-12-21 11:42 UTC, binaek commented
@evanphx I have updated the PR with support for a custom time function - with a default which returns `time.Now()`

Take a look when you get the chance.

2021-12-21 19:15 UTC, evanphx requested changes
Super minor bits, no need to create a closure here, can just use `time.Now` directly.

2021-12-21 19:15 UTC, evanphx commented on global.go
> +		TimeFn: func() time.Time { return time.Now() },
```suggestion
		TimeFn: time.Now,
```

2021-12-21 19:15 UTC, evanphx commented on intlogger.go
> +		timeFn:            func() time.Time { return time.Now() },
```suggestion
		timeFn:            time.Now,
```

2021-12-21 21:13 UTC, binaek commented
Huh! Not sure why I put the closure in there. Let me update the PR when I am at my desk

2021-12-22 07:47 UTC, binaek commented
@evanphx PR updated

2022-01-03 09:55 UTC, binaek commented
@evanphx let me know if you think this requires other changes

2022-01-10 22:04 UTC, merged