Refactor colorization: faster, and one less dependency
hashicorp/go-hclog pull request #106
Opened 2022-02-17 00:50 UTC by dolmen

Refactor colorization (which uses ANSI sequences):
* add non-regression test for colorization 
* faster: drop multiple calls to `fmt.Sprintf` per log message
* drop dependency on `github.com/fatih/color`

2022-02-17 00:50 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/go-hclog?pullRequest=106)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/go-hclog?pullRequest=106)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/go-hclog?pullRequest=106).</sub>

2022-02-18 19:57 UTC, jefferai requested changes
I recommend against merging this.

Fatih's color package is a minimal and clean package with a good abstraction. Its only dependencies are things that go-hclog depends on already (colorizable and isatty). Those packages are also tried and tested on Windows. I'm not sure if this colorize function is.

Overall if your only goal is "eliminate as many dependencies as numerically possible" then this technically gets rid of one dependency, but I don't think it's worth the maintainability and readability cost.

2022-07-25 16:24 UTC, evanphx commented
I'm going to go ahead and close this due to lack of discussion.

2022-07-25 16:24 UTC, closed without merging

2023-06-13 00:16 UTC, dolmen commented
The point of this PR was not just removing one dependency but also make colored logging faster.